### PR TITLE
[back] try to fix Update test

### PR DESCRIPTION
**Pull request by puttimeth**

### CODE REVIEW

**Comment by KombangkoeDias** [comment]
I've seen it too, and I think the clean up sometimes does not work and there's some test-created nont sitter/ owner left in the database. Trying to fix it since two days ago.

**Comment by KombangkoeDias** [comment]
I'll try to merge my hopefully-fixed branch and see if it's fixed.

**Comment by puttimeth** [comment]
Just realize it. When it run in pc, it clean up perfectly but when run with git actions, it doesn't work somehow.

**Comment by puttimeth** [comment]
@KombangkoeDias OK. I will wait.

**Comment by KombangkoeDias** [comment]
After merging, now it seems to work.

**Pull request merged**
