### PR TITLE
Add test for FindShelter

### PR DESCRIPTION
**Pull request by Megacodexz**
- Add test for FindShelter.
- Changes in findShelters in ShelterController. This was done to make testing easier.
- Changes in the front-end file for compatibility.

### CODE REVIEW

**Comment by puttimeth** [comment]
Hope User test part will not fail again. @Megacodexz Do not forget to add your login before test. adios.

**Comment by KombangkoeDias** [comment]
if it says timeout exceed, check for `expect` statements before `done` function, 
When the expect value doesn't match the real value in these `expect` statements, they throw error, causing the `done` coming after get omited, resulting in timeout exceed.

**Comment by Megacodexz** [comment]
It passed! YAY!

**Comment by Megacodexz** [comment]
Some test cases took almost 18 seconds to pass.
Well, it looks like we have some severe performance issues...

**Pull request merged**
