### PR TITLE
Added Router guard !

### PR DESCRIPTION
**Pull request by KombangkoeDias**
Now the router guard prevents un-logged in user to go into guarded routes, and also prevents inappropriate user going into some routes such as a Nont Sitter shouldn't be able to go to /nont routes!. As a fetch for user login data is needed every time the website navigate (for security purpose), if user try to go to inaccessible routes, the component will be rendered and exited as soon as the data is fetched in this version of my router guard.

### CODE REVIEW

**Comment by Megacodexz** [comment]
Splendid! Thank you for your contribution to this project.

**Comment by Megacodexz** [comment]
Why was `nontclient/package-lock.json` deleted? (That is deletion of ~16000 LOC. wow)

**Comment by KombangkoeDias** [comment]
> Why was `nontclient/package-lock.json` deleted? (That is deletion of ~16000 LOC. wow)

since I use yarn and it says we already have the `yarn.lock`, so I thought we should only keep one lock file. You can add it back if you like XD.

**Review by Megacodexz — APPROVED** [review]
It works flawlessly. Approved.

**Comment by KombangkoeDias** [comment]
If no more comments are added, I'll merge the pull request at the end of the day.

**Comment by puttimeth** [comment]
It works great. Approved.

**Review by puttimeth — APPROVED** [review]

**Pull request merged**
