### PR TITLE
Test Starter

### PR DESCRIPTION
**Pull request by KombangkoeDias**
I have added some of the test files for Login, Signup, and Authorization, and I've added the script test and coverage
to test run the test script ie `yarn test`
but if you want to both test and generate coverage report run `yarn coverage`

### CODE REVIEW

**Comment by KombangkoeDias** [comment]
wow just saw the CI auto test, nice 😲

**Comment by KombangkoeDias** [comment]
Will merge this tomorrow morning to facilitate other test implementors.

**Review by puttimeth — APPROVED** [review]
The work is incredible. How long did it take to complete the test after pull request?

**Comment by KombangkoeDias** [comment]
@puttimeth about 10 seconds I think.

**Comment by puttimeth** [comment]
Actually when I try to set up CI, the test keep failing because timeout so I set timeout prefix to 10000 to prevent this happen to other. But it's not happen to you so I'm not sure anymore.

**Comment by KombangkoeDias** [comment]
> Actually when I try to set up CI, the test keep failing because timeout so I set timeout prefix to 10000 to prevent this happen to other. But it's not happen to you so I'm not sure anymore.

Which tests were you using? In my tests, I use the function `done` which prevent the timeout caused by the delayed responses from the server, if I were to remove all the `done` function, it would also result in the timeout error.

**Comment by puttimeth** [comment]
I use the old test, the one that have 3 file. All of them have `done` but when it try to login, the waiting is so long it throw timeout, after I set timeout to 10000, the problem seem to solve completely.

**Comment by KombangkoeDias** [comment]
Hmm, that's strange. After I added `done` in the old test, the timeout error was gone completely. We can add it back to be safe though.

**Comment by puttimeth** [comment]
I think we should add `.nyc_output` folder to `.gitignore`. What do you think? @KombangkoeDias

**Comment by KombangkoeDias** [comment]
agree, I'll merge it first before adding, on the Internet, it also says that the coverage folder should be added to `.gitignore` as well, will also do that

**Pull request merged**
